# Generated by Django 5.0.3 on 2024-04-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
